### ISSUE TITLE
Broken Extension

### ISSUE THREAD

**Issue by shafi49** [alessandrio/brackets-open-in-browser#24]
Hey, thanks for this extension. I have been using this extension for quite a while... This morning I updated your extension. After the update your extension is acting strangely. It is not opening files in browser. There may be some serious issue. Please fix this as soon as possible ...

**Comment by DH3ALEJANDRO** [comment]
please your browser info.

**Comment by shafi49** [comment]
OS: Windows 10 64bit,
Default Browser: Google Chrome.

I want to be more specific here...
The extension is not opening full path in the browser. Instead it is splitting the file path in three different sections. The three broken snippet of file path opens in three different tab of my browser. 
Example:
 " file:///C:/Users/SHAFI " opens first in a tab.
" http://ul/ " and " http://bari/Desktop/treehouse-Portfolio/index.html " opens in two separate tabs of my browser. 
Needless to say " file:///C:/Users/SHAFIulBARI/Desktop/treehouse-Portfolio/index.html " is the actual file path...

**Comment by DH3ALEJANDRO** [comment]
try several times and can not find the error. your browser is in the new version?

**Comment by shafi49** [comment]
yes, my browser is updated... 
actually, its like /SHAFI%20ul%20BARI/ ....

**Comment by DH3ALEJANDRO** [comment]
Please upgrade from github

**Comment by shafi49** [comment]
ok... 
Thanks for your support ...
